package com.parkloyalty.lpr.scan.utility

object SerializedNameKeys {
    //LOGIN KEY
    const val ID = "id"
    const val first_name = "first_name"
    const val last_name = "last_name"
    const val dateofBirth = "date_of_birth"
    const val qr_code_image = "qr_code_image"
    const val city = "city"
    const val address1 = "address1"
    const val address = "address"
    const val postalCode = "postalCode"
    const val mobile = "mobile"
    const val token = "token"
    const val profile_image = "profile_image"
    const val user_id = "user_id"
    const val state = "state"
    const val lang = "lang"
    const val email = "email"
    const val otp = "otp"
    const val pin = "pin"
    const val zip_code = "zip_code"
    const val c_register_firstname = "c_register_firstname"
    const val c_register_lastname = "c_register_lastname"
    const val c_register_dob = "c_register_dob"
    const val c_register_phone = "c_register_phone"
    const val c_register_email = "c_register_email"
    const val c_register_country = "c_register_country"
    const val c_register_state = "c_register_state"
    const val c_register_zipcode = "c_register_zipcode"
    const val c_register_address = "c_register_address"
    const val c_card_number = "c_card_number"
    const val c_expire_month = "c_expire_month"
    const val c_expire_year = "c_expire_year"
    const val c_security_code = "c_security_code"
    const val c_zip_code = "c_zip_code"
    const val c_id_type = "c_id_type"
    const val bank_name = "bank_name"
    const val bank_code = "bank_code"
    const val branch_name = "branch_name"
    const val bank_address = "bank_address"
    const val is_deleted = "is_deleted"
    const val created_at = "created_at"
    const val updated_at = "updated_at"
    const val created_by = "created_by"
    const val updated_by = "updated_by"
}