package com.parkloyalty.lpr.scan.util

interface ReportArrayClass {
    companion object {
        val mZone2ndForAllReport = arrayOf("B: N. Hollywood: North Lot",
            "B: N. Hollywood: South Lot",
            "B: N. Hollywood: East Lot",
            "B: N. Hollywood: West Lot",
            "B: Universal City: North Lot",
            "B: Universal City: West Lot",
            "B: Universal City: South Lot",
            "B: Vermont/Beverly",
            "B: Westlake/MacArthur Park Lot",
            "B: Vermont/Santa Monica",
            "B: Vermont/Sunset",
            "B: Pershing Square",
            "B: Civic Center/Grand Park",
            "B: Hollywood/Highland",
            "E: Expo/ Crenshaw Structure",
            "K: Fairview Heights Lot",
            "D: Wilshire/Vermont",
            "D: Wilshire/Western",
            "D: Wilshire/Normandie",
            "Union Station: 800 N Alameda St, Los Angeles, CA 90012",
            "E: Culver City Structure",
            "E: Expo/Sepulveda Structure",
            "E: Expo/Bundy Lot",
            "E: 17th Street/SMC Lot",
            "E: La Cienega/Jefferson Structure",
            "E: Atlantic: Parking Structure",
            "E: Atlantic: Northeast Lot",
            "E: South Pasadena",
            "E: Indiana Lot",
            "K: El Segundo Lot",
            "K: Douglas",
            "K: Redondo Beach: North Lot",
            "K: Redondo Beach: South Lot",
            "C: Norwalk: Access",
            "C: Lynwood West Lot",
            "C: Lynwood East Lot",
            "C: Avalon: North Lot",
            "C: Avalon: Northeast Lot",
            "C: Harbor Freeway Lot",
            "C: Vermont/Athens Lot",
            "C: Crenshaw Lot",
            "C: Aviation/Imperial Lot",
            "C: Hawthorne/Lennox: East Lot",
            "C: Hawthorne/Lennox: West Lot",
            "C: Lakewood: South Lot",
            "C: Lakewood: North Lot",
            "C: Norwalk: East Lot",
            "C: Norwalk: West Lot",
            "G: Chatsworth: South Lot",
            "G: Chatsworth: North Lot",
            "G: Sherman Way: East Lot",
            "G: Sherman Way: West Lot",
            "G: Canoga Lot",
            "G: Pierce College Lot",
            "G: Reseda: Southeast Lot",
            "G: Reseda: Southwest Lot",
            "G: Reseda: Northwest Lot",
            "G: Balboa Lot",
            "G: Sepulveda Lot",
            "G: Van Nuys: South Lot",
            "G: Van Nuys: North Lot",
            "A: Del Amo Lot",
            "A: Willowbrook/Rosa Parks: South Lot",
            "A: Willowbrook/Rosa Parks: North Lot",
            "A: Artesia Lot",
            "A: Wardlow: North Lot",
            "A: Wardlow: South Lot",
            "A: Willow: South Lot",
            "A: Willow: Southwest Structure",
            "A: Willow: North Lot",
            "A: Florence Lot",
            "A: Azusa Downtown Structure",
            "A: Sierra Madre Villa Structure",
            "A: Monrovia Structure",
            "A: Duarte/City of Hope Lot",
            "A: Irwindale Structure",
            "A: Arcadia: Structure",
            "A: Arcadia: Lot",
            "A: Lake Lot",
            "A Del Mar Lot",
            "A: APU/Citrus Structure",
            "A: Lincoln/Cyrpess Lot",
            "A: Heritage Square Lot",
            "A: Fillmore Structure",
            "J: El Monte: Northeast Lot",
            "J: El Monte: West Lot",
            "J: El Monte: West Structure",
            "J: El Monte: East Lot",
            "J: El Monte: Southeast Lot",
            "J: El Monte: Gunderson Lot",
            "J: Slauson: West Lot",
            "J: Slauson: East Lot",
            "J: Manchester: West Lot",
            "J: Manchester: East Lot",
            "J: Harbor Gateway Transit Center Lot",
            "J: Rosecrans Lot",
            "J: PCH Lot",
            "J: Carson Lot",
            "J: Harbor Beacon Lot",
            "Metro Division 2 Employee Lot",
            "Division 5 Employee Lot",
            "Metro Property",
            "MTA Property",
            "A: Glendora",
            "A: Glendora: Lot 1",
            "A: Glendora: Lot 2",
            "A: San Dimas",
            "A: La Verne/Fairplex",
            "A: Pomona North",
            "A: Pomona North Lot 1",
            "A: Pomona North Lot 2")

        val mZoneForTowAnd72Hour = arrayOf(
            "B: N. Hollywood: North Lot: 11230 Cumpston Street, North Hollywood, CA 91601",
            "B: N. Hollywood: South Lot: 11240 Chandler Blvd., North Hollywood, CA 91601",
            "B: N. Hollywood: East Lot: 11143 Chandler Blvd., North Hollywood, CA 91601",
            "B: N. Hollywood: West Lot: 11346 Chandler Blvd., North Hollywood, CA 91601",
            "B: Universal City: North Lot: 3901 Lankershim Blvd., Los Angeles, CA 91604",
            "B: Universal City: West Lot: 10801 Ventura Blvd., Los Angeles, CA 91604",
            "B: Universal City: South Lot: 10700 Ventura Blvd. Los Angeles, CA 91604",
            "B: Vermont/Beverly: 301 North Vermont Avenue Los Angeles, CA 90004",
            "B: Westlake/MacArthur Park: 685 S. Westlake Avenue, Los Angeles, CA 90057",
            "B: Vermont/Santa Monica: 1015 North Vermont Avenue Los Angeles, CA 90029",
            "B: Vermont/Sunset: 1500 North Vermont Avenue Los Angeles, CA 90027",
            "B: Pershing Square: 500 South Hill Street Los Angeles, CA 90013",
            "B: Civic Center/Grand Park: 101 South Hill Street Los Angeles, CA 90013",
            "B: Hollywood/Highland: 6815 Hollywood Boulevard Hollywood, CA 90028",
            "E: Expo/ Crenshaw: 3500 Crenshaw Blvd, Los Angeles, CA 90018",
            "K: Fairview Heights: 1130 E. Redondo Blvd, Inglewood, CA",
            "D: Wilshire/Vermont: 3191 Wilshire Boulevard Los Angeles, CA 90005",
            "D: Wilshire/Western: 3775 Wilshire Blvd. Los Angeles, CA 90005",
            "D: Wilshire/Normandie: 3510 Wilshire Boulevard Los Angeles, CA 90005",
            "Union Station: 800 N Alameda St, Los Angeles, CA 90012",
            "E: Culver City: 8840 National Blvd, Culver City, CA 90232",
            "E: Expo/Sepulveda: 11214 Exposition Blvd., Los Angeles, CA 90064",
            "E: Expo/Bundy: 2101 S. Bundy Drive, Los Anageles, CA 90064",
            "E: 17th Street/SMC: 1610 Colorado Avenue, Santa Monica, CA 90404",
            "E: La Cienega/Jefferson: 3420 S. La Cienega Blvd., Los Angeles, CA 90016",
            "E: Atlantic: Parking Structure: 255 S. Atlantic Blvd. Los Angeles, CA 90022",
            "E: Atlantic: Northeast Lot: 255 S. Atlantic Blvd. Los Angeles, CA 90022",
            "E: South Pasadena: 807 Meridian Ave., South Pasadena, CA 91030",
            "E: Indiana: 177 S. Alma Avenue, Los Angeles, CA 90063",
            "K: El Segundo: 2226 E. El Segundo Blvd., El Segundo, CA 90245",
            "K: Douglas: 700 S. Douglas Street, El Segundo, CA 90245",
            "K: Redondo Beach: North Lot: 2406 Marine Avenue, Redondo Beach, CA 90260",
            "K: Redondo Beach: South Lot: 2406 Marine Avenue, Redondo Beach, CA 90260",
            "C: Norwalk: Access: 12901 Hoxie Avenue, Norwalk, CA 90650",
            "C: Lynwood West Lot: 11455 Lynwood Blvd. Lynwood, CA 90262",
            "C: Lynwood East Lot: 11508 Lynwood Blvd. Lynwood, CA 90262",
            "C: Avalon: North Lot: 652 East 116th Place, Los Angeles , CA 90059",
            "C: Avalon: Northeast Lot: 672 East 116th Place, Los Angeles, CA 90059",
            "C: Harbor Freeway: 11600 S. Figueroa Street, Los Angeles, CA 90061",
            "C: Vermont/Athens: 114 S. Vermont Avenue, Los Angeles, CA 90044",
            "C: Crenshaw: 3200 West 120h Street, Hawthorne, CA 90250",
            "C: Aviation/Imperial: 5574 W. Imperial Highway, Los Angeles, CA 90045",
            "C: Hawthorne/Lennox: East Lot: 4335 West 111th Street, Inglewood, CA 90304",
            "C: Hawthorne/Lennox: West Lot: 4445 West 111th Street, Inglewood, CA 90304",
            "C: Lakewood: South Lot: 12875 Lakewood Blvd. Downey, CA 90242",
            "C: Lakewood: North Lot: 12775 Lakewood Blvd. Downey, CA 90242",
            "C: Norwalk: East Lot: 12901 Hoxie Avenue, Norwalk, CA 90650",
            "C: Norwalk: West Lot: 12901 Hoxie Avenue, Norwalk, CA 90650",
            "G: Chatsworth: South Lot: 10005 Old Depot Plaza Road, Los Angeles, CA 91311",
            "G: Chatsworth: North Lot: 10046 Old Depot Plaza Road, Los Angeles, CA 91311",
            "G: Sherman Way: East Lot: 7119 Deering Avenue,Los Angeles, CA 91303",
            "G: Sherman Way: West Lot: 7170 Canoga Avenue, Los Angeles, CA 91303",
            "G: Canoga: 6650 Canoga Avenue, Los Angeles, CA 91303",
            "G: Pierce College: 20245 Victory Blvd. Los Angeles, CA 91367",
            "G: Reseda: Southeast Lot: 18450 Oxnard Street, Los Angeles, CA 91356",
            "G: Reseda: Southwest Lot: 18548 Oxnard Street, Los Angeles, CA 91356",
            "G: Reseda: Northwest Lot: 18530 Topham Street, Los Angeles, CA 91355",
            "G: Balboa: 6338 Balboa Blvd, Encino, CA 91316",
            "G: Sepulveda: 15330 W. Erwin Street, Los Angeles, CA 91411",
            "G: Van Nuys: South Lot: 11415 Aetna Street, Los Angeles, CA 91401",
            "G: Van Nuys: North Lot: 14612 Bessemer Street, Los Angeles, CA 91411",
            "A: Del Amo: 20485 Santa Fe Avenue, Compton, CA 90221",
            "A: Willowbrook/Rosa Parks: South Lot- 11711 South Wilmington Avenue, Los Angeles, CA 90059",
            "A: Willowbrook/Rosa Parks: North Lot: 11644 Willowbrook Avenue, Los Angeles , CA 90059",
            "A: Artesia: 1920 1/2 Arcadia Avenue, Compton, CA 90220",
            "A: Wardlow: North Lot: 3440 Pacific Place, Lynwood, CA 90806",
            "A: Wardlow: South Lot: 3380 Pacific Place, Lynwood, CA 90806",
            "A: Willow: South Lot: 2750 West American Avenue, Lynwood, CA 90806",
            "A: Willow: Southwest Structure: 200 East 27th Street, Lynwood, CA 90806",
            "A: Willow: North Lot: 2750 West American Avenue, Lynwood, CA 90806",
            "A: Florence: 7225 Graham Avenue, Los Angeles, CA 90001",
            "A: 103rd Street Watts Towers: 10400 Grandee Avenue, Los Angeles, CA 90002",
            "A: Azusa Downtown: 801 N. Alameda Avenue, Azusa, CA 91762",
            "A: Sierra Madre Villa: 149 N. Halstead , Pasadena , CA 91107",
            "A: Monrovia: 1641 S. Primrose Ave. Monrovia, CA 91606",
            "A: Duarte/City of Hope: 1789 Fasana Rd Duarte, CA 91010",
            "A: Irwindale: 15998 Avenida Padilla, Irwindale, CA 91702",
            "A: Arcadia: Structure: 73 E. Santa Clara St, Arcadia, CA 91006",
            "A: Arcadia: Lot: 73 E. Santa Clara St, Arcadia, CA 91006",
            "A: Lake: 367 Maple Way, Pasadena, CA 91101",
            "A Del Mar: 202 S. Raymond Avenue, Pasadena, CA 91105",
            "A: APU/Citrus: 901 B North Citrus Ave. Azusa , CA 91762",
            "A: Lincoln/Cyrpess: 370 W. Avenue 26, Los Angeles, CA 90031",
            "A: Heritage Square: 3545 Pasadena Avenue, Los Angeles, CA 90031",
            "A: Fillmore: 750 S. Raymond Avenue, Pasadena, CA 91105",
            "J: El Monte: Northeast Lot: 3501 Santa Anita Avenue, El Monte, CA 91731",
            "J: El Monte: West Lot: 3501 Santa Anita Avenue, El Monte, CA 91731",
            "J: El Monte: West Structure: 3501 Santa Anita Avenue, El Monte, CA 91731",
            "J: El Monte: East Lot: 3501 Santa Anita Avenue, El Monte, CA 91731",
            "J: El Monte: Southeast Lot: 3343 Santa Anita Avenue, El Monte, CA 91731",
            "J: El Monte: Gunderson Lot: 3333 Santa Anita Ave, El Monte, CA 91731",
            "J: Slauson: West Lot: 430 W. Slauson Avenue, Los Angeles, CA 90003",
            "J: Slauson: East Lot: 350 W. Slauson Avenue, Los Angeles, CA 90003",
            "J: Manchester: West Lot: 431 W. Manchester Avenue, Los Angeles, CA 90003",
            "J: Manchester: East Lot: 390 W. Manchester Avenue, Los Angeles, CA 90003",
            "J: Harbor Gateway Transit Center: 731 W. 182nd Street, Gardena, CA 90248",
            "J: Rosecrans: 622 W. Rosecrans Avenue, Gardena, CA 90248",
            "J: PCH: 1345 W. Pacific Coast Highway, Wilmington, CA 90744",
            "J: Carson: 705 W. Carson Street, Torrance, CA 90502",
            "J: Harbor Beacon: 515 N. Beacon St, San Pedro, CA",
            "Metro Division 2 Employee Lot: 1695 Griffith Ave, Los Angeles, CA 90021",
            "Division 5 Employee Lot: 5425 S. Van Ness, Los Angles, CA",
            "Metro Property: 9530 Alondra Blvd, Bellflower, CA 90706",
            "MTA Property: 13015 Raymer St, North Hollywood, CA",
            "A: Glendora: 410 S Vermont Ave, Glendora, CA 91741",
            "A: Glendora: Lot 1: 410 S Vermont Ave, Glendora, CA 91741",
            "A: Glendora: Lot 2: 410 S Vermont Ave, Glendora, CA 91741",
            "A: San Dimas: 124 W Railway St, San Dimas, CA 91773",
            "A: La Verne/Fairplex: Fairplex Drive & Arrow Hwy, La Verne, CA 91750",
            "A: Pomona North: 207 Santa Fe St, Pomona, CA 91767",
            "A: Pomona North Lot 1: 205 Santa Fe St., Pomona, CA 91767",
            "A: Pomona North Lot 2: 207 Santa Fe St., Pomona, CA 91767")

        val mTowingOfficerListTowReport = arrayOf("Maria Matar",
            "Ara Papajanian",
            "Jorge Monterrojas",
            "Estefania Patino",
            "Elmer Estrada",
            "Carlos Cazal",
            "Ricardo Casarrubias")


    }


}